import type { NextPage } from 'next'
import { useContext, useEffect, useState } from 'react'
import Head from 'next/head'
import { Layout } from '../components'
import { AnimatePresence } from 'framer-motion'
import Prompt from '../components/prompt'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Penpoint</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full min-h-screen relative bg-zinc-900'>
        <Layout>
          <AnimatePresence>
            <Prompt />
            <div className='absolute left-48 top-16 w-content-width h-sidebar-height p-4'>
            </div>
          </AnimatePresence>
        </Layout>
      </main>
    </>
  )
}

export default Home
